Add uname command
mattnite/zigbox pull request #2
Opened 2020-10-20 08:16 UTC by hdorio

Uses `std.os.uname().machine` in place of the deprecated `std.builtin.arch` in the `arch` command.
Adds the `uname` command.
Adds usage/--help messages.

2020-10-21 05:18 UTC, mattnite requested changes
Looks awesome, just have a couple of small notes, thank you for your contribution!

2020-10-21 05:18 UTC, mattnite commented on src/commands.zig
> +    const params = comptime [_]clap.Param(clap.Help){
Clap is able to parse "documentation" strings at comptime to generate these param structs, it compacts the code a bit but more importantly makes it awesome to read. [here](https://github.com/mattnite/zkg/blob/ffdc17352887aab767858802b7c5506585db3813/src/main.zig#L96) is an example for one of the subcommands in zkg. You can do either short and/or long argument names, and ones with values just need to be followed with `<var>`, the important part there is the angle brackets not the "var".

2020-10-21 05:18 UTC, mattnite commented on src/commands.zig
> +    if (args.flag("-s") or args.flag("-a") or !(args.flag("-s") or args.flag("-r") or args.flag("-v") or args.flag("-m") or args.flag("-a"))) {
this should be simplified to:
```
a or s or (!r and !v and !m)
```

2020-10-21 06:09 UTC, hdorio commented on src/commands.zig
> +    const params = comptime [_]clap.Param(clap.Help){
I tried that but Clap will make the compiler throw a `evaluation exceeded 1000 backwards branches` error if I add more than 6 params. Do you want me to fiddle with `@setEvalBranchQuota`?

2020-10-21 06:21 UTC, hdorio commented on src/commands.zig
> +    if (args.flag("-s") or args.flag("-a") or !(args.flag("-s") or args.flag("-r") or args.flag("-v") or args.flag("-m") or args.flag("-a"))) {
done

2020-10-22 02:07 UTC, mattnite commented on src/commands.zig
> +    const params = comptime [_]clap.Param(clap.Help){
Yeah the eval quota is set relatively small, I've found that I generally need to twiddle with it if I'm doing comptime. A good rule of thumb is to get it within 500, and iirc it's platform/hardware agnostic so we don't have to worry about it down the line

2020-10-22 10:14 UTC, hdorio commented on src/commands.zig
> +    const params = comptime [_]clap.Param(clap.Help){
All right, I bumped branch quota from 1000 to 1500.

2020-10-23 07:29 UTC, merged